name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4==4.9.0
        pip install tabulate
        pip install backoff
        python --version
        ls .
    - name: Run collections scraper
      run: |
        python --version
        python scrapers/get_collections.py
        cat output/collections.json
    - name: Commit files
      run: |
        echo $GITHUB_ACTOR
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config --local user.name "$GITHUB_ACTOR"
        git add .
        git status
        git commit -a -m "Initialize new repository from template"
        git push https://${{ secrets.GH_TOKEN }}@github.com/fedorov/actcianable.git
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
